"""
Apply a transformation generated by the SimpleReg application to an image.

Reuses the exact same resampling logic as the GUI (`simplereg.gui.window`), via
the shared functions in `simplereg.core.transform`.

Can be used as a Python script:

.. code:: python

    from simplereg.apply import apply_transform
    apply_transform(
        moving_path="moving.nii.gz",
        fixed_path="fixed.nii.gz",
        transform_path="transform_itk.txt",
        output_path="moving_aligned.nii.gz",
        interpolation="linear",
    )

Or from the command line:

.. code:: bash

    simplereg_apply -i moving.nii.gz -d fixed.nii.gz -w transform_itk.txt -o out.nii.gz -x linear

Benjamin De Leener
Copyright (c) 2025 Polytechnique Montreal <www.neuro.polymtl.ca>
License: see the file LICENSE
"""

import argparse

from .core.image import Image
from .core.transform import (
    INTERPOLATION_MODES,
    apply_label_transform,
    read_transform_from_file,
    resample_image_on_grid,
)

INTERPOLATION_CHOICES = (*INTERPOLATION_MODES.keys(), 'label')


def apply_transform(moving_path, fixed_path, transform_path, output_path, interpolation='linear'):
    """
    Apply an affine transform to `moving_path`, resampled onto the grid of `fixed_path`,
    and save the result to `output_path`.

    :param moving_path: path to the image to transform.
    :param fixed_path: path to the reference/destination image (defines the output grid).
    :param transform_path: path to the transform file (ITK .txt/.tfm, 4x4/3x4 text matrix, or .npy).
    :param output_path: path where the transformed image is saved.
    :param interpolation: one of 'nn', 'linear', 'spline', 'label'.
    """
    if interpolation not in INTERPOLATION_CHOICES:
        raise ValueError(f"Invalid interpolation '{interpolation}'. Choose one of {INTERPOLATION_CHOICES}.")

    moving_img = Image(moving_path)
    fixed_img = Image(fixed_path)
    affine_matrix = read_transform_from_file(transform_path)

    if interpolation == 'label':
        output_img = apply_label_transform(fixed_img, moving_img, affine_matrix)
    else:
        output_img = resample_image_on_grid(
            fixed_img, moving_img, affine_matrix, interpolation_mode=INTERPOLATION_MODES[interpolation]
        )

    output_img.save(output_path)
    return output_img


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="simplereg_apply",
        description="Apply a transformation generated by SimpleReg to an image."
    )
    parser.add_argument("-i", dest="input", required=True, help="Image to transform (moving image).")
    parser.add_argument("-d", dest="dest", required=True,
                        help="Reference/destination image defining the output grid (fixed image).")
    parser.add_argument("-w", dest="warp", required=True, help="Transformation file.")
    parser.add_argument("-o", dest="output", required=True, help="Output file name.")
    parser.add_argument(
        "-x", dest="interpolation", choices=INTERPOLATION_CHOICES, default="linear",
        help="""Interpolation method: nn, linear, spline, label.

Note: The `label` method is a special interpolation method designed for single-
voxel labels (e.g. disc labels used as registration landmarks, compression
labels, etc.). This method is necessary because classical interpolation may
corrupt the values of single-voxel labels, or cause them to disappear entirely.
The function works by dilating each label, applying the transformation using
nearest neighbour interpolation, then extracting the center-of-mass of each
transformed 'blob' to get a single-voxel output label. Because the output is a
single-voxel label, the `-x label` method is not appropriate for multi-voxel
labeled segmentations (such as spinal cord or lesion masks).
(default: linear)"""
    )

    args = parser.parse_args(argv)

    apply_transform(
        moving_path=args.input,
        fixed_path=args.dest,
        transform_path=args.warp,
        output_path=args.output,
        interpolation=args.interpolation,
    )


if __name__ == "__main__":
    main()
